Repository CA-G12/SamBook-Ibtisam-Salsabeel, pull requests merged in 2022-09, with the labels that each got.

#3 Editing App File to being CLass
  src/App.js
Labels: done

#5 4 fetch api
  package-lock.json
  package.json
  public/index.html
  src/components/BookCard.js
  src/components/BookInfo.js
  src/components/Cards.js
  src/components/VideoCard.js
  src/components/fetchData.js
Labels: approved

#7 Fetching Main data from API
  src/App.js
  src/components/BookCard.js
  src/components/Cards.js
  src/components/Header.js
  src/components/SearchBar.js
  src/components/fetchData.js
Labels: waiting-Review

#10 fix the enter word
  src/components/BookCard.js
  src/components/Header.js
  src/components/SearchBar.js
Labels: approved

#12 9 create popup for book info
  src/App.css
  src/components/BookCard.js
  src/components/BookInfo.js
  src/components/Header.js
  src/components/SearchBar.js
  src/index.css
  src/index.js
Labels: approved
